# CMP 464 Midterm Project: Predicting Housing Prices at Ames, Iowa, Part II

# IV. Identify additional relevant feature

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import zipfile
import folium
%matplotlib inline

In [2]:
#1. Find features with high correlation
# First let load the data as a pandas DataFrame.
url = "https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data/train.csv"
House_price = pd.read_csv('train.csv')
House_price.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [3]:
# Let calculate the correlation coeficient of House_price
House_price.corr()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
Id,1.000000,0.011156,-0.010601,-0.033226,-0.028365,0.012609,-0.012713,-0.021998,-0.050298,-0.005024,...,-0.029643,-0.000477,0.002889,-0.046635,0.001330,0.057044,-0.006242,0.021172,0.000712,-0.021917
MSSubClass,0.011156,1.000000,-0.386347,-0.139781,0.032628,-0.059316,0.027850,0.040581,0.022936,-0.069836,...,-0.012579,-0.006100,-0.012037,-0.043825,-0.026030,0.008283,-0.007683,-0.013585,-0.021407,-0.084284
LotFrontage,-0.010601,-0.386347,1.000000,0.426095,0.251646,-0.059213,0.123349,0.088866,0.193458,0.233633,...,0.088521,0.151972,0.010700,0.070029,0.041383,0.206167,0.003368,0.011200,0.007450,0.351799
LotArea,-0.033226,-0.139781,0.426095,1.000000,0.105806,-0.005636,0.014228,0.013788,0.104160,0.214103,...,0.171698,0.084774,-0.018340,0.020423,0.043160,0.077672,0.038068,0.001205,-0.014261,0.263843
OverallQual,-0.028365,0.032628,0.251646,0.105806,1.000000,-0.091932,0.572323,0.550684,0.411876,0.239666,...,0.238923,0.308819,-0.113937,0.030371,0.064886,0.065166,-0.031406,0.070815,-0.027347,0.790982
OverallCond,0.012609,-0.059316,-0.059213,-0.005636,-0.091932,1.000000,-0.375983,0.073741,-0.128101,-0.046231,...,-0.003334,-0.032589,0.070356,0.025504,0.054811,-0.001985,0.068777,-0.003511,0.043950,-0.077856
YearBuilt,-0.012713,0.027850,0.123349,0.014228,0.572323,-0.375983,1.000000,0.592855,0.315707,0.249503,...,0.224880,0.188686,-0.387268,0.031355,-0.050364,0.004950,-0.034383,0.012398,-0.013618,0.522897
YearRemodAdd,-0.021998,0.040581,0.088866,0.013788,0.550684,0.073741,0.592855,1.000000,0.179618,0.128451,...,0.205726,0.226298,-0.193919,0.045286,-0.038740,0.005829,-0.010286,0.021490,0.035743,0.507101
MasVnrArea,-0.050298,0.022936,0.193458,0.104160,0.411876,-0.128101,0.315707,0.179618,1.000000,0.264736,...,0.159718,0.125703,-0.110204,0.018796,0.061466,0.011723,-0.029815,-0.005965,-0.008201,0.477493
BsmtFinSF1,-0.005024,-0.069836,0.233633,0.214103,0.239666,-0.046231,0.249503,0.128451,0.264736,1.000000,...,0.204306,0.111761,-0.102303,0.026451,0.062021,0.140491,0.003571,-0.015727,0.014359,0.386420
BsmtFinSF2,-0.005968,-0.065649,0.049900,0.111170,-0.059119,0.040229,-0.049107,-0.067759,-0.072319,-0.050117,...,0.067898,0.003093,0.036543,-0.029993,0.088871,0.041709,0.004940,-0.015211,0.031706,-0.011378
BsmtUnfSF,-0.007940,-0.140759,0.132644,-0.002618,0.308159,-0.136841,0.149040,0.181133,0.114442,-0.495251,...,-0.005316,0.129005,-0.002538,0.020764,-0.012579,-0.035092,-0.023837,0.034888,-0.041258,0.214479
TotalBsmtSF,-0.015415,-0.238518,0.392075,0.260833,0.537808,-0.171098,0.391452,0.291066,0.363936,0.522396,...,0.232019,0.247264,-0.095478,0.037384,0.084489,0.126053,-0.018479,0.013196,-0.014969,0.613581
1stFlrSF,0.010496,-0.251758,0.457181,0.299475,0.476224,-0.144203,0.281986,0.240379,0.344501,0.445863,...,0.235459,0.211671,-0.065292,0.056104,0.088758,0.131525,-0.021096,0.031372,-0.013604,0.605852
2ndFlrSF,0.005590,0.307886,0.080177,0.050986,0.295493,0.028942,0.010308,0.140024,0.174561,-0.137079,...,0.092165,0.208026,0.061989,-0.024358,0.040606,0.081487,0.016197,0.035164,-0.028700,0.319334
LowQualFinSF,-0.044230,0.046474,0.038469,0.004779,-0.030429,0.025494,-0.183784,-0.062419,-0.069071,-0.064503,...,-0.025444,0.018251,0.061081,-0.004296,0.026799,0.062157,-0.003793,-0.022174,-0.028921,-0.025606
GrLivArea,0.008273,0.074853,0.402797,0.263116,0.593007,-0.079686,0.199010,0.287389,0.390857,0.208171,...,0.247433,0.330224,0.009113,0.020643,0.101510,0.170205,-0.002416,0.050240,-0.036526,0.708624
BsmtFullBath,0.002289,0.003491,0.100949,0.158155,0.111098,-0.054942,0.187599,0.119470,0.085310,0.649212,...,0.175315,0.067341,-0.049911,-0.000106,0.023148,0.067616,-0.023047,-0.025361,0.067049,0.227122
BsmtHalfBath,-0.020155,-0.002333,-0.007234,0.048046,-0.040150,0.117821,-0.038162,-0.012337,0.026673,0.067418,...,0.040161,-0.025324,-0.008555,0.035114,0.032121,0.020025,-0.007367,0.032873,-0.046524,-0.016844
FullBath,0.005587,0.131608,0.198769,0.126031,0.550600,-0.194149,0.468271,0.439046,0.276833,0.058543,...,0.187703,0.259977,-0.115093,0.035353,-0.008106,0.049604,-0.014290,0.055872,-0.019669,0.560664
HalfBath,0.006784,0.177354,0.053532,0.014259,0.273458,-0.060769,0.242656,0.183331,0.201444,0.004262,...,0.108080,0.199740,-0.095317,-0.004972,0.072426,0.022381,0.001290,-0.009050,-0.010269,0.284108
BedroomAbvGr,0.037719,-0.023438,0.263170,0.119690,0.101676,0.012980,-0.070651,-0.040581,0.102821,-0.107355,...,0.046854,0.093810,0.041570,-0.024478,0.044300,0.070703,0.007767,0.046544,-0.036014,0.168213
KitchenAbvGr,0.002951,0.281721,-0.006069,-0.017784,-0.183882,-0.087001,-0.174800,-0.149598,-0.037610,-0.081007,...,-0.090130,-0.070091,0.037312,-0.024600,-0.051613,-0.014525,0.062341,0.026589,0.031687,-0.135907
TotRmsAbvGrd,0.027239,0.040380,0.352096,0.190015,0.427452,-0.057583,0.095589,0.191740,0.280682,0.044316,...,0.165984,0.234192,0.004151,-0.006683,0.059383,0.083757,0.024763,0.036907,-0.034516,0.533723
Fireplaces,-0.019772,-0.045569,0.266639,0.271364,0.396765,-0.023820,0.147716,0.112581,0.249070,0.260011,...,0.200019,0.169405,-0.024822,0.011257,0.184530,0.095074,0.001409,0.046357,-0.024096,0.466929
GarageYrBlt,0.000072,0.085072,0.070250,-0.024947,0.547766,-0.324297,0.825667,0.642277,0.252691,0.153484,...,0.224577,0.228425,-0.297003,0.023544,-0.075418,-0.014501,-0.032417,0.005337,-0.001014,0.486362
GarageCars,0.016570,-0.040110,0.285691,0.154871,0.600671,-0.185758,0.537850,0.420622,0.364204,0.224054,...,0.226342,0.213569,-0.151434,0.035765,0.050494,0.020934,-0.043080,0.040522,-0.039117,0.640409
GarageArea,0.017634,-0.098672,0.344997,0.180403,0.562022,-0.151521,0.478954,0.371600,0.373066,0.296970,...,0.224666,0.241435,-0.121777,0.035087,0.051412,0.061047,-0.027400,0.027974,-0.027378,0.623431
WoodDeckSF,-0.029643,-0.012579,0.088521,0.171698,0.238923,-0.003334,0.224880,0.205726,0.159718,0.204306,...,1.000000,0.058661,-0.125989,-0.032771,-0.074181,0.073378,-0.009551,0.021011,0.022270,0.324413
OpenPorchSF,-0.000477,-0.006100,0.151972,0.084774,0.308819,-0.032589,0.188686,0.226298,0.125703,0.111761,...,0.058661,1.000000,-0.093079,-0.005842,0.074304,0.060762,-0.018584,0.071255,-0.057619,0.315856
EnclosedPorch,0.002889,-0.012037,0.010700,-0.018340,-0.113937,0.070356,-0.387268,-0.193919,-0.110204,-0.102303,...,-0.125989,-0.093079,1.000000,-0.037305,-0.082864,0.054203,0.018361,-0.028887,-0.009916,-0.128578
3SsnPorch,-0.046635,-0.043825,0.070029,0.020423,0.030371,0.025504,0.031355,0.045286,0.018796,0.026451,...,-0.032771,-0.005842,-0.037305,1.000000,-0.031436,-0.007992,0.000354,0.029474,0.018645,0.044584
ScreenPorch,0.001330,-0.026030,0.041383,0.043160,0.064886,0.054811,-0.050364,-0.038740,0.061466,0.062021,...,-0.074181,0.074304,-0.082864,-0.031436,1.000000,0.051307,0.031946,0.023217,0.010694,0.111447
PoolArea,0.057044,0.008283,0.206167,0.077672,0.065166,-0.001985,0.004950,0.005829,0.011723,0.140491,...,0.073378,0.060762,0.054203,-0.007992,0.051307,1.000000,0.029669,-0.033737,-0.059689,0.092404
MiscVal,-0.006242,-0.007683,0.003368,0.038068,-0.031406,0.068777,-0.034383,-0.010286,-0.029815,0.003571,...,-0.009551,-0.018584,0.018361,0.000354,0.031946,0.029669,1.000000,-0.006495,0.004906,-0.021190
MoSold,0.021172,-0.013585,0.011200,0.001205,0.070815,-0.003511,0.012398,0.021490,-0.005965,-0.015727,...,0.021011,0.071255,-0.028887,0.029474,0.023217,-0.033737,-0.006495,1.000000,-0.145721,0.046432
YrSold,0.000712,-0.021407,0.007450,-0.014261,-0.027347,0.043950,-0.013618,0.035743,-0.008201,0.014359,...,0.022270,-0.057619,-0.009916,0.018645,0.010694,-0.059689,0.004906,-0.145721,1.000000,-0.028923
SalePrice,-0.021917,-0.084284,0.351799,0.263843,0.790982,-0.077856,0.522897,0.507101,0.477493,0.386420,...,0.324413,0.315856,-0.128578,0.044584,0.111447,0.092404,-0.021190,0.046432,-0.028923,1.000000

In [4]:
# Base on the coeficient distribution we can cite : OverallQual, TotalBsmtSF, GrLivArea, 1stFlrSF, GarageCars, GarageArea, SalePrice
# Let calculate their correlation coefficient with feature SalePrice. 
# OverallQual
House_price['OverallQual'].corr(House_price['SalePrice'])

0.7909816005838046

In [5]:
# TotalBsmtSF
House_price['TotalBsmtSF'].corr(House_price['SalePrice'])

0.6135805515591953

In [6]:
# GrLivArea
House_price['GrLivArea'].corr(House_price['SalePrice'])

0.7086244776126518

In [7]:
# 1stFlrSF
House_price['1stFlrSF'].corr(House_price['SalePrice'])

0.6058521846919147

In [8]:
# GarageCars
House_price['GarageCars'].corr(House_price['SalePrice'])

0.6404091972583529

In [9]:
# GarageArea
House_price['GarageArea'].corr(House_price['SalePrice'])

0.6234314389183616

In [10]:
# SalePrice
House_price['SalePrice'].corr(House_price['SalePrice'])

0.9999999999999998

In [11]:
# The feature (other than a forementioned 5 features) that has the strongest correlation with the sale prices is:
# GarageCars

In [12]:
# 2. Feature engineering: 
#1) total area = total area above ground (“GrLivArea”) + total basement area (“TotalBsmtSF”)
TotalArea = House_price['GrLivArea'] + House_price['TotalBsmtSF']
TotalArea.head()

0    2566
1    2524
2    2706
3    2473
4    3343
dtype: int64

In [13]:
#2) area per room = total area above ground (“GrLivArea”) / number of rooms (“TotRmsAbvGrd”)
area_per_room = House_price['GrLivArea'] / House_price['TotRmsAbvGrd']
area_per_room.head()

0    213.750000
1    210.333333
2    297.666667
3    245.285714
4    244.222222
dtype: float64

In [14]:
Feature_engineering = pd.DataFrame({'TotalArea':House_price['GrLivArea'] + House_price['TotalBsmtSF'],
                          'AreaPerRoom' :House_price['GrLivArea'] / House_price['TotRmsAbvGrd']})
Feature_engineering.head()

   TotalArea  AreaPerRoom
0       2566   213.750000
1       2524   210.333333
2       2706   297.666667
3       2473   245.285714
4       3343   244.222222

# V. Prepare data for k-Nearest-Neighbor method

In [15]:
# 1. Create a new data frame with SalePrice and the 7 selected features
# Let extract the first 6 features we know before 
relevant_features = ['OverallQual','YearBuilt','TotalBsmtSF','GrLivArea','TotRmsAbvGrd','SalePrice']
House_price = House_price.filter(relevant_features, axis=1)
House_price.head()

   OverallQual  YearBuilt  TotalBsmtSF  GrLivArea  TotRmsAbvGrd  SalePrice
0            7       2003          856       1710             8     208500
1            6       1976         1262       1262             6     181500
2            7       2001          920       1786             6     223500
3            7       1915          756       1717             7     140000
4            8       2000         1145       2198             9     250000

In [17]:
# Then let add TotalArea and AreaPerRoom to the releavant features in order to have SalePrice and 7 selected features
New_data_frame = pd.concat([House_price, Feature_engineering], axis = 1)
New_data_frame.head()

,OverallQual,YearBuilt,TotalBsmtSF,GrLivArea,TotRmsAbvGrd,SalePrice,TotalArea,AreaPerRoom
0,7,2003,856,1710,8,208500,2566,213.750000
1,6,1976,1262,1262,6,181500,2524,210.333333
2,7,2001,920,1786,6,223500,2706,297.666667
3,7,1915,756,1717,7,140000,2473,245.285714
4,8,2000,1145,2198,9,250000,3343,244.222222

In [18]:
# 2. For each of the 7 selected features, calculate its standard deviation.
# Let remove SalePrice from New data frame
data = New_data_frame.drop('SalePrice', axis = 1)
data.head()

,OverallQual,YearBuilt,TotalBsmtSF,GrLivArea,TotRmsAbvGrd,TotalArea,AreaPerRoom
0,7,2003,856,1710,8,2566,213.750000
1,6,1976,1262,1262,6,2524,210.333333
2,7,2001,920,1786,6,2706,297.666667
3,7,1915,756,1717,7,2473,245.285714
4,8,2000,1145,2198,9,3343,244.222222

In [19]:
# standard deviation of 7 features
data.std()

OverallQual       1.382997
YearBuilt        30.202904
TotalBsmtSF     438.705324
GrLivArea       525.480383
TotRmsAbvGrd      1.625393
TotalArea       823.598492
AreaPerRoom      44.740397
dtype: float64

# VI. Apply the kNN (k=5) method to predict sale price of the first instance from the test set.

In [20]:
# 1. Load test.csv and extract its first row. Calculate its total area and area per room.
url = 'https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data?select=test1.csv'
test_data = pd.read_csv('test1.csv')
test_data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [21]:
# Extract the first row
test_data_1 = test_data.loc[[0], :]
test_data_1

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal

In [22]:
#2. Add a new column (“Diff”) to the data frame representing the training data
# First let calculate total area = total area above ground (“GrLivArea”) + total basement area (“TotalBsmtSF”)
TotalArea = test_data['GrLivArea'] + test_data['TotalBsmtSF']
TotalArea.head()

0    1778.0
1    2658.0
2    2557.0
3    2530.0
4    2560.0
dtype: float64

In [31]:
# 2nd area per room = total area above ground (“GrLivArea”) / number of rooms (“TotRmsAbvGrd”)
AreaPerRoom = test_data['GrLivArea'] / test_data['TotRmsAbvGrd']
AreaPerRoom.head()

0    179.200000
1    221.500000
2    271.500000
3    229.142857
4    256.000000
dtype: float64

In [32]:
# let extract the relevant commun featuresfrom test data frame
relevant_features_test = ['OverallQual','YearBuilt','TotalBsmtSF','GrLivArea','TotRmsAbvGrd']
test_data = test_data.filter(relevant_features_test, axis=1)
test_data.head()

   OverallQual  YearBuilt  TotalBsmtSF  GrLivArea  TotRmsAbvGrd
0            5       1961        882.0        896             5
1            6       1958       1329.0       1329             6
2            5       1997        928.0       1629             6
3            6       1998        926.0       1604             7
4            8       1992       1280.0       1280             5

In [33]:
# let create a fuction that will generate all values of Total Area 

def TotalArea (test_data):
    
    return test_data['GrLivArea'] + test_data['TotalBsmtSF']

In [34]:
TotalArea(test_data.loc[0, :])

1778.0

In [35]:
# Let apply a column TotalArea to the test_data frame 
test_data['TotalArea'] = test_data.apply(TotalArea, axis = 1)
test_data.head()

   OverallQual  YearBuilt  TotalBsmtSF  GrLivArea  TotRmsAbvGrd  TotalArea
0            5       1961        882.0        896             5     1778.0
1            6       1958       1329.0       1329             6     2658.0
2            5       1997        928.0       1629             6     2557.0
3            6       1998        926.0       1604             7     2530.0
4            8       1992       1280.0       1280             5     2560.0

In [36]:
# let create a fuction that will generate all values of area per room 

def AreaPerRoom (test_data):
    
    return  test_data['GrLivArea'] / test_data['TotRmsAbvGrd']

In [37]:
AreaPerRoom(test_data.loc[0, :])

179.2

In [38]:
# let add the column AreaPerRoom to the test_data frame
test_data['AreaPerRoom'] = test_data.apply(AreaPerRoom, axis = 1)
test_data.head()

,OverallQual,YearBuilt,TotalBsmtSF,GrLivArea,TotRmsAbvGrd,TotalArea,AreaPerRoom
0,5,1961,882.0,896,5,1778.0,179.200000
1,6,1958,1329.0,1329,6,2658.0,221.500000
2,5,1997,928.0,1629,6,2557.0,271.500000
3,6,1998,926.0,1604,7,2530.0,229.142857
4,8,1992,1280.0,1280,5,2560.0,256.000000

In [39]:
test_data_1 = test_data.loc[[0], :]
test_data_1

,OverallQual,YearBuilt,TotalBsmtSF,GrLivArea,TotRmsAbvGrd,TotalArea,AreaPerRoom
0,5,1961,882.0,896,5,1778.0,179.2

In [40]:
#2. Add a new column (“Diff”) to the data frame representing the training data. 
#For each row, calculate a weighted sum of the differences between this row’s features and those from the test row.
#For each feature, use the reciprocal of its standard deviation as its weight.
# data['Diff'] = diff * 1/data.std()
    
data['Diff'] = np.abs(data['OverallQual'] - test_data['OverallQual']) * (1/data['OverallQual'].std()) + \
               np.abs(data['YearBuilt'] - test_data['YearBuilt']) * (1/data['YearBuilt'].std())+ \
               np.abs(data['TotalBsmtSF'] - test_data['TotalBsmtSF']) * (1/data['TotalBsmtSF'].std()) + \
               np.abs(data['GrLivArea'] - test_data['GrLivArea']) * (1/data['GrLivArea'].std()) + \
               np.abs(data['TotRmsAbvGrd'] - test_data['TotRmsAbvGrd']) * (1/data['TotRmsAbvGrd'].std()) + \
               np.abs(data['TotalArea'] - test_data['TotalArea']) * (1/data['TotalArea'].std()) + \
               np.abs(data['AreaPerRoom'] - test_data['AreaPerRoom']) * (1/data['AreaPerRoom'].std())

data.head()

,OverallQual,YearBuilt,TotalBsmtSF,GrLivArea,TotRmsAbvGrd,TotalArea,AreaPerRoom,Diff
0,7,2003,856,1710,8,2566,213.750000,8.019771
1,6,1976,1262,1262,6,2524,210.333333,1.288482
2,7,2001,920,1786,6,2706,297.666667,2.661351
3,7,1915,756,1717,7,2473,245.285714,4.503713
4,8,2000,1145,2198,9,3343,244.222222,5.994468

In [41]:
# 3. Sort the rows so that values in the “Diff” column is listed in ascending order.
#The top 5 instances are the closest neighbors of the new instance y. 
# k = 5
data = data.sort_values(by=['Diff'])
data.head()

,OverallQual,YearBuilt,TotalBsmtSF,GrLivArea,TotRmsAbvGrd,TotalArea,AreaPerRoom,Diff
1050,7,2007,1302,1302,6,2604,217.000000,0.396971
931,5,1965,925,925,5,1850,185.000000,0.509060
1449,5,1970,630,630,3,1260,210.000000,0.723068
857,6,1994,702,1481,6,2183,246.833333,0.762478
950,5,1950,864,864,5,1728,172.800000,0.874467

In [42]:
# 4. Calculate the average sale price of these 5 instances. This will be the prediction of the new instance.
# we know the indeces of these 5 instances index = [1050,931,1449,857,950]
# Let extract the SalePrice of these 5 instances

New_data_frame[['SalePrice']].iloc[[1050,931,1449,857,950]]

      SalePrice
1050     176485
931      117500
1449      92000
857      174000
950      129000

In [44]:
# Calculate the average sale price of these 5 instances. This will be the prediction of the new instance
prediction_new_instance = New_data_frame[['SalePrice']].iloc[[1050,931,1449,857,950]].mean()
print("Prediction:", prediction_new_instance)

Prediction: SalePrice    137797.0
dtype: float64